// Generates DESIGN.md from the single design-truth modules (SPEC §2). Never
// hand-edit DESIGN.md — run `pnpm design:doc`. Runs under Node's type stripping,
// so relative imports carry explicit .ts extensions.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { PALETTE } from '../src/uno/palette.ts';
import { STEP, FONT } from '../src/uno/tachyons.ts';
import { hexToHsl, isColorLawCompliant } from '../src/uno/hue.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../DESIGN.md');

/** Per-kernel spot assignment (mirrors src/styles/modes/*.css). */
const KERNEL_SPOTS: ReadonlyArray<readonly [string, string]> = [
  ['essential', 'achromatic — spot resolves to ink, no riso'],
  ['brutal', 'Riso Orange `#FF6C2F`'],
  ['clay', 'Riso Green `#00A95C` + Sunflower Yellow `#FFE800` highlight'],
  ['generative', 'achromatic over the ink/paper duotone canvas'],
];

const paletteRows = Object.entries(PALETTE)
  .map(([name, hex]) => {
    const { h, s } = hexToHsl(hex);
    const law = isColorLawCompliant(hex) ? '✓' : '✗ FORBIDDEN';
    const kind = s < 0.1 ? 'achromatic' : `${Math.round(h)}°`;
    return `| \`${name}\` | \`${hex}\` | ${kind} | ${(s * 100).toFixed(0)}% | ${law} |`;
  })
  .join('\n');

const spacingRows = Object.entries(STEP)
  .map(([step, value]) => `| \`${step}\` | \`${value}\` |`)
  .join('\n');

const typeRows = [
  ...Object.entries(FONT).map(([step, value]) => `| \`f${step}\` | \`${value}\` |`),
  '| `f-subheadline` | `5rem` |',
  '| `f-headline` | `6rem` |',
  '| `--type-display` | fluid, per mode kernel |',
].join('\n');

const kernelRows = KERNEL_SPOTS.map(([mode, spot]) => `| \`${mode}\` | ${spot} |`).join('\n');

const doc = `<!-- GENERATED by \`pnpm design:doc\` from uno.config.ts — DO NOT EDIT. -->

# DESIGN — token reference

The single design truth is \`uno.config.ts\` (palette + Tachyons vocabulary) and
the mode kernels in \`src/styles/modes/*.css\`. This file is regenerated from
them; hand edits are overwritten. Live reference: [/design](./src/pages/design.astro).

## Color law

Chrome never uses blue, red, or purple. Allowed hue territory is
yellow→orange→green (15°–180°); everything else is forbidden (red 345°–15°,
blue/cyan 180°–270°, purple 270°–345°). Near-achromatic ink tints are exempt.
Every token below is verified by \`test/color-law.test.ts\`.

| Token | Hex | Hue | Sat | Law |
| --- | --- | --- | --- | --- |
${paletteRows}

## Kernel spot inks

| Mode | Spot |
| --- | --- |
${kernelRows}

## Spacing scale (Tachyons steps, applied via \`p*\`/\`m*\`/\`n*\`)

| Step | Value |
| --- | --- |
${spacingRows}

## Type scale (Tachyons \`f1–f7\` + display steps)

| Utility | Size |
| --- | --- |
${typeRows}

Families (two total, self-hosted): **Archivo** variable (display + body),
**IBM Plex Mono** (labels, meta, nav rail).
`;

writeFileSync(outPath, doc, 'utf8');
process.stdout.write(`design:doc → wrote ${outPath}\n`);
